In [2]:
from bs4 import BeautifulSoup
import requests

In [3]:
import pandas as pd

In [4]:
r = requests.get('https://api.usno.navy.mil/moon/phase?year=2018')

In [5]:
print(r.text)

{
      "error":false,
      "apiversion":"2.2.1",
      "year":2018,
      "month":1,
      "day":1,
      "numphases":50,
      "datechanged":false,
      "phasedata":[
            {
               "phase":"Full Moon",
               "date":"2018 Jan 02",
               "time":"02:24"
            },
            {
               "phase":"Last Quarter",
               "date":"2018 Jan 08",
               "time":"22:25"
            },
            {
               "phase":"New Moon",
               "date":"2018 Jan 17",
               "time":"02:17"
            },
            {
               "phase":"First Quarter",
               "date":"2018 Jan 24",
               "time":"22:20"
            },
            {
               "phase":"Full Moon",
               "date":"2018 Jan 31",
               "time":"13:27"
            },
            {
               "phase":"Last Quarter",
               "date":"2018 Feb 07",
               "time":"15:54"
            },
            {
               "phase":"New Moon",
               "date":"2018 Feb 15",
               "time":"21:05"
            },
            {
               "phase":"First Quarter",
               "date":"2018 Feb 23",
               "time":"08:09"
            },
            {
               "phase":"Full Moon",
               "date":"2018 Mar 02",
               "time":"00:51"
            },
            {
               "phase":"Last Quarter",
               "date":"2018 Mar 09",
               "time":"11:20"
            },
            {
               "phase":"New Moon",
               "date":"2018 Mar 17",
               "time":"13:12"
            },
            {
               "phase":"First Quarter",
               "date":"2018 Mar 24",
               "time":"15:35"
            },
            {
               "phase":"Full Moon",
               "date":"2018 Mar 31",
               "time":"12:37"
            },
            {
               "phase":"Last Quarter",
               "date":"2018 Apr 08",
               "time":"07:17"
            },
            {
               "phase":"New Moon",
               "date":"2018 Apr 16",
               "time":"01:57"
            },
            {
               "phase":"First Quarter",
               "date":"2018 Apr 22",
               "time":"21:46"
            },
            {
               "phase":"Full Moon",
               "date":"2018 Apr 30",
               "time":"00:58"
            },
            {
               "phase":"Last Quarter",
               "date":"2018 May 08",
               "time":"02:09"
            },
            {
               "phase":"New Moon",
               "date":"2018 May 15",
               "time":"11:48"
            },
            {
               "phase":"First Quarter",
               "date":"2018 May 22",
               "time":"03:49"
            },
            {
               "phase":"Full Moon",
               "date":"2018 May 29",
               "time":"14:19"
            },
            {
               "phase":"Last Quarter",
               "date":"2018 Jun 06",
               "time":"18:32"
            },
            {
               "phase":"New Moon",
               "date":"2018 Jun 13",
               "time":"19:43"
            },
            {
               "phase":"First Quarter",
               "date":"2018 Jun 20",
               "time":"10:51"
            },
            {
               "phase":"Full Moon",
               "date":"2018 Jun 28",
               "time":"04:53"
            },
            {
               "phase":"Last Quarter",
               "date":"2018 Jul 06",
               "time":"07:51"
            },
            {
               "phase":"New Moon",
               "date":"2018 Jul 13",
               "time":"02:48"
            },
            {
               "phase":"First Quarter",
               "date":"2018 Jul 19",
               "time":"19:52"
            },
            {
               "phase":"Full Moon",
               "date":"2018 Jul 27",
               "time":"20:20"
            },
            {
               "phase":"Last Quarter",
               "date":"2018 Aug 04",
               "time":"18:18"
            },
            {
               "phase":"New Moon",
               "date":"2018 Aug 11",
               "time":"09:58"
            },
            {
               "phase":"First Quarter",
               "date":"2018 Aug 18",
               "time":"07:48"
            },
            {
               "phase":"Full Moon",
               "date":"2018 Aug 26",
               "time":"11:56"
            },
            {
               "phase":"Last Quarter",
               "date":"2018 Sep 03",
               "time":"02:37"
            },
            {
               "phase":"New Moon",
               "date":"2018 Sep 09",
               "time":"18:01"
            },
            {
               "phase":"First Quarter",
               "date":"2018 Sep 16",
               "time":"23:15"
            },
            {
               "phase":"Full Moon",
               "date":"2018 Sep 25",
               "time":"02:52"
            },
            {
               "phase":"Last Quarter",
               "date":"2018 Oct 02",
               "time":"09:45"
            },
            {
               "phase":"New Moon",
               "date":"2018 Oct 09",
               "time":"03:47"
            },
            {
               "phase":"First Quarter",
               "date":"2018 Oct 16",
               "time":"18:02"
            },
            {
               "phase":"Full Moon",
               "date":"2018 Oct 24",
               "time":"16:45"
            },
            {
               "phase":"Last Quarter",
               "date":"2018 Oct 31",
               "time":"16:40"
            },
            {
               "phase":"New Moon",
               "date":"2018 Nov 07",
               "time":"16:02"
            },
            {
               "phase":"First Quarter",
               "date":"2018 Nov 15",
               "time":"14:54"
            },
            {
               "phase":"Full Moon",
               "date":"2018 Nov 23",
               "time":"05:39"
            },
            {
               "phase":"Last Quarter",
               "date":"2018 Nov 30",
               "time":"00:19"
            },
            {
               "phase":"New Moon",
               "date":"2018 Dec 07",
               "time":"07:20"
            },
            {
               "phase":"First Quarter",
               "date":"2018 Dec 15",
               "time":"11:49"
            },
            {
               "phase":"Full Moon",
               "date":"2018 Dec 22",
               "time":"17:49"
            },
            {
               "phase":"Last Quarter",
               "date":"2018 Dec 29",
               "time":"09:34"
            }
      ]
   }

In [6]:
response = requests.get('https://api.usno.navy.mil/moon/phase?year=2018')
data = response.json()

In [7]:
len(data)

8

In [8]:
moonphase = data['phasedata']

In [9]:
pd.DataFrame(moonphase)

           date          phase   time
0   2018 Jan 02      Full Moon  02:24
1   2018 Jan 08   Last Quarter  22:25
2   2018 Jan 17       New Moon  02:17
3   2018 Jan 24  First Quarter  22:20
4   2018 Jan 31      Full Moon  13:27
5   2018 Feb 07   Last Quarter  15:54
6   2018 Feb 15       New Moon  21:05
7   2018 Feb 23  First Quarter  08:09
8   2018 Mar 02      Full Moon  00:51
9   2018 Mar 09   Last Quarter  11:20
10  2018 Mar 17       New Moon  13:12
11  2018 Mar 24  First Quarter  15:35
12  2018 Mar 31      Full Moon  12:37
13  2018 Apr 08   Last Quarter  07:17
14  2018 Apr 16       New Moon  01:57
15  2018 Apr 22  First Quarter  21:46
16  2018 Apr 30      Full Moon  00:58
17  2018 May 08   Last Quarter  02:09
18  2018 May 15       New Moon  11:48
19  2018 May 22  First Quarter  03:49
20  2018 May 29      Full Moon  14:19
21  2018 Jun 06   Last Quarter  18:32
22  2018 Jun 13       New Moon  19:43
23  2018 Jun 20  First Quarter  10:51
24  2018 Jun 28      Full Moon  04:53
25  2018 Jul 06   Last Quarter  07:51
26  2018 Jul 13       New Moon  02:48
27  2018 Jul 19  First Quarter  19:52
28  2018 Jul 27      Full Moon  20:20
29  2018 Aug 04   Last Quarter  18:18
30  2018 Aug 11       New Moon  09:58
31  2018 Aug 18  First Quarter  07:48
32  2018 Aug 26      Full Moon  11:56
33  2018 Sep 03   Last Quarter  02:37
34  2018 Sep 09       New Moon  18:01
35  2018 Sep 16  First Quarter  23:15
36  2018 Sep 25      Full Moon  02:52
37  2018 Oct 02   Last Quarter  09:45
38  2018 Oct 09       New Moon  03:47
39  2018 Oct 16  First Quarter  18:02
40  2018 Oct 24      Full Moon  16:45
41  2018 Oct 31   Last Quarter  16:40
42  2018 Nov 07       New Moon  16:02
43  2018 Nov 15  First Quarter  14:54
44  2018 Nov 23      Full Moon  05:39
45  2018 Nov 30   Last Quarter  00:19
46  2018 Dec 07       New Moon  07:20
47  2018 Dec 15  First Quarter  11:49
48  2018 Dec 22      Full Moon  17:49
49  2018 Dec 29   Last Quarter  09:34

In [10]:
for i in range(2012,2020):
    response = requests.get('https://api.usno.navy.mil/moon/phase?year={}'.format(i))
    data = response.json()
    moonphase.append(data['phasedata'])

In [11]:
moonphase[0]

{'phase': 'Full Moon', 'date': '2018 Jan 02', 'time': '02:24'}

In [14]:
df = pd.DataFrame()

In [15]:
for i in range(len(moonphase)):
    df = df.append(pd.DataFrame(moonphase[i]))

ValueError: If using all scalar values, you must pass an index

In [1]:
df = df.reset_index().drop('index', axis = 1)

NameError: name 'df' is not defined

In [140]:
df.head()

          date          phase   time
0  2012 Jan 01  First Quarter  06:15
1  2012 Jan 09      Full Moon  07:30
2  2012 Jan 16   Last Quarter  09:08
3  2012 Jan 23       New Moon  07:39
4  2012 Jan 31  First Quarter  04:10

In [141]:
import csv

In [142]:
df.to_csv('moonphasedf.csv')

In [ ]:
df['']